name: Selenide CI with Maven to Final Surge Tests

on:
  schedule:
   - cron: '40 00 1-31/2 * *'
   - cron: '00 10 * * 3,5'
   - cron: '40 10 2-31/2 * 3'
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: ["master", "development" ]
  workflow_dispatch:
    inputs:
      suite:
        description: 'Choose a browser'
        required: true
        default: 'chrome'
        options:
          - smoke
          - regression    

jobs:
  smoke_suite:
    runs-on: windows-latest
    if: github.event.schedule == '40 00 1-31/2 * *' || github.event.inputs.suite == 'smoke'

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    
    - name: Run Smoke Tests
      run: mvn -B clean test -DsuiteName=smoke 

    - name: Generate Allure Report
      if: always()
      run: mvn allure:report

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{github.run_id}}
        path: target/allure-report

  regression_suite:
    runs-on: windows-latest
    if: github.event.schedule == '00 10 * * 3,5' || github.event.inputs.suite == 'regression'

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    
    - name: Run Smoke Tests
      run: mvn -B clean test -DsuiteName=regression

    - name: Generate Allure Report
      if: always()
      run: mvn allure:report

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{github.run_id}}
        path: target/allure-report
        
  alltime_alltests_suite:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    
    - name: Run Smoke Tests
      run: mvn -B clean test -DsuiteName=allTests

    - name: Generate Allure Report
      if: always()
      run: mvn allure:report

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{github.run_id}}
        path: target/allure-report
